on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 216.14.124.9
        protocol: sftp
        port: 2223
        username: cloudtech
        password: AEIRC@1234-Nepal
        local-dir: ./
        server-dir: /home/cloudtech/aeirc.tech/